### ISSUE TITLE
Error reading JToken from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by cchrkk** [Shades84/Homemeter-Rainassistant#1]
![image](https://user-images.githubusercontent.com/12370126/118839862-298c5f00-b8c7-11eb-910f-2677c22e8fcb.png)

Hey, any idea why that happens? 
Tried to reinstall Rainmeter to latest beta, installed jsonparsed, tested my bearer and it's working with reqbin. Maybe some update broke it?

Thanks 🙏

**Comment by Shades84** [comment]
If you open the 'Skin' tab in that same window, and select the test_sensor skin, do all the variables look right? The entity_id, ha_addr, and ha_auth, in particular. Check the 'HAapi' measure and see that it is not blank; im guessing it is.

**Comment by cchrkk** [comment]
> If you open the 'Skin' tab in that same window, and select the test_sensor skin, do all the variables look right? The entity_id, ha_addr, and ha_auth, in particular. Check the 'HAapi' measure and see that it is not blank; im guessing it is.

![image](https://user-images.githubusercontent.com/12370126/118945762-0bba0b00-b956-11eb-93df-de1f53b798fb.png)
![image](https://user-images.githubusercontent.com/12370126/118946308-88e58000-b956-11eb-97de-ed629cc65fad.png)

Yep 404, but why? 🤔

**Comment by Shades84** [comment]
Do you have the port set with the rainmeter skin? Also, I have not tested this suite with dns addresses so that might be an issue too

**Comment by cchrkk** [comment]
![image](https://user-images.githubusercontent.com/12370126/119108311-5acc7280-ba20-11eb-8cfe-a1492a16f38c.png)
Adding :443 at the end of my endpoint worked and it looks like rainmeter gets the value, but the parsing is not working?

I still have that JsonReader error. Maybe it has something do with my curl installation

```
curl 7.76.1 (x86_64-pc-win32) libcurl/7.76.1 OpenSSL/1.1.1k (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 WinIDN libssh2/1.9.0 nghttp2/1.43.0 libgsasl/1.10.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP Unicode UnixSockets zstd
```

**Comment by Shades84** [comment]
That is curious. Curl should be working if HAapi is getting a value. Can you copy the string it gives? Also, the HAparse section of the skin  is unmodified, right? It might be some sort of type issue (float, int, string, etc)

**Comment by BlackNine1** [comment]
Dunno if this helps, but I had the same issue where I had downloaded the 32bit Json dll. Changed to the 64 bit and it started working

**Comment by cchrkk** [comment]
> Dunno if this helps, but I had the same issue where I had downloaded the 32bit Json dll. Changed to the 64 bit and it started working

~~Uhm, that's right. Using x86 JsonParser on my x64 Rainmeter fixed the problem. 🤷~~

EDIT: Not true, I got tricked because the widget had a 0 in it (instead of blank widget)
Now unable to load the plugin because it's for a wrong arch, still having that issue. Very weird!
